#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# enabling PEP8 tests
from tests.other.PEP8 import Flake8Test

# enabling package tests: interfaces, functions, etc...
from Satel.tests.dataReader import DataReaderTest, FunctionsTest

# enabling satel EthernetDataReader test
from Satel.tests.ethernetDataReader import EthernetDataReaderTest

# enabling satel DataParser tests
from Satel.tests.dataParser import DataParserTest

# enabling byte functions tests
from Satel.tests.byteFunctions import FunctionsTest

# enabling satel Integra tests
from Satel.tests.integra import DefaultIntegraTests, Integra128Test, Integra24Test, Integra256Test, Integra32Test, Integra64Test
from Satel.tests.detector import DetectorTest
from Satel.tests.out import OutTest