# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SystemEditor.ui'
#
# Created: Mon Nov 10 14:37:26 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_SystemEditor(object):
    def setupUi(self, SystemEditor):
        SystemEditor.setObjectName(_fromUtf8("SystemEditor"))
        SystemEditor.resize(762, 625)
        self.gridLayout = QtGui.QGridLayout(SystemEditor)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_5 = QtGui.QLabel(SystemEditor)
        self.label_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        self.lstSystems = QtGui.QListWidget(SystemEditor)
        self.lstSystems.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lstSystems.setAlternatingRowColors(True)
        self.lstSystems.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.lstSystems.setObjectName(_fromUtf8("lstSystems"))
        self.verticalLayout.addWidget(self.lstSystems)
        self.widget = QtGui.QWidget(SystemEditor)
        self.widget.setMinimumSize(QtCore.QSize(0, 20))
        self.widget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.btnDelSystem = QtGui.QPushButton(self.widget)
        self.btnDelSystem.setGeometry(QtCore.QRect(0, 0, 71, 23))
        self.btnDelSystem.setObjectName(_fromUtf8("btnDelSystem"))
        self.btnAddSystem = QtGui.QPushButton(self.widget)
        self.btnAddSystem.setGeometry(QtCore.QRect(130, 0, 71, 23))
        self.btnAddSystem.setObjectName(_fromUtf8("btnAddSystem"))
        self.verticalLayout.addWidget(self.widget)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(SystemEditor)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.txtSystemName = QtGui.QLineEdit(SystemEditor)
        self.txtSystemName.setObjectName(_fromUtf8("txtSystemName"))
        self.verticalLayout_2.addWidget(self.txtSystemName)
        self.label_6 = QtGui.QLabel(SystemEditor)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_2.addWidget(self.label_6)
        self.txtIPAddress = QtGui.QLineEdit(SystemEditor)
        self.txtIPAddress.setObjectName(_fromUtf8("txtIPAddress"))
        self.verticalLayout_2.addWidget(self.txtIPAddress)
        self.label_7 = QtGui.QLabel(SystemEditor)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_2.addWidget(self.label_7)
        self.txtIntegrationPort = QtGui.QLineEdit(SystemEditor)
        self.txtIntegrationPort.setObjectName(_fromUtf8("txtIntegrationPort"))
        self.verticalLayout_2.addWidget(self.txtIntegrationPort)
        self.tabWidget = QtGui.QTabWidget(SystemEditor)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabDetectors = QtGui.QWidget()
        self.tabDetectors.setObjectName(_fromUtf8("tabDetectors"))
        self.cmbDetectors = QtGui.QComboBox(self.tabDetectors)
        self.cmbDetectors.setGeometry(QtCore.QRect(20, 10, 411, 23))
        self.cmbDetectors.setObjectName(_fromUtf8("cmbDetectors"))
        self.label_2 = QtGui.QLabel(self.tabDetectors)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 101, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.txtDetectorName = QtGui.QLineEdit(self.tabDetectors)
        self.txtDetectorName.setGeometry(QtCore.QRect(130, 50, 311, 22))
        self.txtDetectorName.setObjectName(_fromUtf8("txtDetectorName"))
        self.tabWidget.addTab(self.tabDetectors, _fromUtf8(""))
        self.tabOuts = QtGui.QWidget()
        self.tabOuts.setObjectName(_fromUtf8("tabOuts"))
        self.cmbOuts = QtGui.QComboBox(self.tabOuts)
        self.cmbOuts.setGeometry(QtCore.QRect(20, 10, 411, 23))
        self.cmbOuts.setObjectName(_fromUtf8("cmbOuts"))
        self.label_3 = QtGui.QLabel(self.tabOuts)
        self.label_3.setGeometry(QtCore.QRect(30, 50, 101, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.txtOutName = QtGui.QLineEdit(self.tabOuts)
        self.txtOutName.setGeometry(QtCore.QRect(140, 50, 311, 22))
        self.txtOutName.setObjectName(_fromUtf8("txtOutName"))
        self.tabWidget.addTab(self.tabOuts, _fromUtf8(""))
        self.tabZones = QtGui.QWidget()
        self.tabZones.setObjectName(_fromUtf8("tabZones"))
        self.cmbZones = QtGui.QComboBox(self.tabZones)
        self.cmbZones.setGeometry(QtCore.QRect(20, 10, 411, 23))
        self.cmbZones.setObjectName(_fromUtf8("cmbZones"))
        self.label_4 = QtGui.QLabel(self.tabZones)
        self.label_4.setGeometry(QtCore.QRect(30, 50, 101, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.txtZoneName = QtGui.QLineEdit(self.tabZones)
        self.txtZoneName.setGeometry(QtCore.QRect(130, 50, 311, 22))
        self.txtZoneName.setObjectName(_fromUtf8("txtZoneName"))
        self.tabWidget.addTab(self.tabZones, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.btnSaveChanges = QtGui.QPushButton(SystemEditor)
        self.btnSaveChanges.setObjectName(_fromUtf8("btnSaveChanges"))
        self.verticalLayout_2.addWidget(self.btnSaveChanges)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(SystemEditor)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(SystemEditor)

    def retranslateUi(self, SystemEditor):
        SystemEditor.setWindowTitle(QtGui.QApplication.translate("SystemEditor", "Edytor systemów", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("SystemEditor", "Lista systemów:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDelSystem.setText(QtGui.QApplication.translate("SystemEditor", "Usuń", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddSystem.setText(QtGui.QApplication.translate("SystemEditor", "Dodaj", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("SystemEditor", "Nazwa systemu:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("SystemEditor", "Adres IP:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("SystemEditor", "Port integracji", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("SystemEditor", "Nazwa wejścia", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDetectors), QtGui.QApplication.translate("SystemEditor", "Wejścia", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("SystemEditor", "Nazwa wyjścia", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOuts), QtGui.QApplication.translate("SystemEditor", "Wyjścia", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("SystemEditor", "Nazwa strefy", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabZones), QtGui.QApplication.translate("SystemEditor", "Strefy", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSaveChanges.setText(QtGui.QApplication.translate("SystemEditor", "Zapisz zmiany", None, QtGui.QApplication.UnicodeUTF8))

